# --------------------
# Spring Boot Framework / Service Configuration
# Prefix: service.*
# --------------------
service:
  context-path: /schedule/iqe
  #  encrypt:
  #    method: JASYPT
  #    jasypt:
  #      key: ${JASYPT_KEY}
  logging:
    #   Supported mode: CVSEVENT, LOGAPP
    level:
      root: INFO
      com:
        cvshealth:
          digital: INFO
    pattern:
      console: "%msg%n"
    #   Supported destinations: CONSOLE, HTTP
    #   For HTTP, set log-app.url
    #   List of events to ignore while logging. Valid: ENTRY, EXIT, INFO, EXIT
    ignore-events:
      - ENTRY
    excluded-endpoints:
      - "/actuator*/**"
      - "/swagger*/**"
      - "/v3/api*/**"
      - "/metrics/**"
      - "/scheduling/iqe/actuator*/**"
      - "/scheduling/iqe/swagger*/**"
      - "/scheduling/iqe/health*/**"


  # Redis Configuration. prefix: service.redis-cache
  redis-cache:
    enabled: true
    strategy: "dataset-snapshot"  # Strategy 1: Dataset Snapshot with Scheduled Refresh
    baseUrl: https://internal-uat-test-east.digital-healthservices.cvs.com/cache/v1
    readTimeout: 100
    writeTimeout: 100
    connectionTimeout: 10000
    timeoutErrorMessage: SERVICE_UNAVAILABLE
    headers:
      - contentType: application/json
      - accept: application/json
    redisFlag: true
    cacheType: questionnaire_dataset_6h_noextend
    
    dataset-refresh:
      enabled: true
      interval-hours: 4           # Refresh every 4 hours
      batch-size: 100            # Process in batches
      timeout-minutes: 30        # Max refresh time
      retry-attempts: 3          # Retry failed refreshes
      
    response-caching:
      enabled: false             # Explicitly disabled
      
    dataset-keys:
      rules-prefix: "dataset:rules_by_flow:"
      actions-key: "dataset:actions"
      questions-prefix: "dataset:questions:"
      answer-options-prefix: "dataset:answer_options:"
      details-prefix: "dataset:questions_details:"
      metadata-key: "dataset:metadata"
      
    read-strategy:
      cassandra-first: true       # Cassandra as primary data source
      redis-fallback-only: true   # Redis only during Cassandra outages
      timeout-ms: 5000           # Cassandra read timeout
      retry-attempts: 2          # Retry failed Cassandra reads
      
    fallback:
      cassandra-timeout: "5s"
      redis-timeout: "2s"
      circuit-breaker:
        enabled: true
        failure-threshold: 3   # Reduced threshold for faster failover
        recovery-timeout: "30s"
        sliding-window-size: 10


# Spring Configuration
spring:
  application:
    name: dhs-scheduling-iqe-service
    version: v1
  config:
    import:
      - classpath:/dhs-scheduling-messages.yaml

  mvc:
    throw-exception-if-no-handler-found: true
    pathmatch:
      matching-strategy: ant_path_matcher
  web:
    resources:
      add-mappings: false
    main:
      web-application-type: reactive
      banner-mode: off
      allow-bean-definition-overriding: true
    jpa:
      open-in-view: false
    graphql:
      path: /dhs/scheduling/graphql
      graphiql:
        enabled: true
    webflux:
      base-path: ""
  data:
    cassandra:
      # session-name: cvs-planogram-svc
      #mfedev, mfeqa
      session-leak:
        threshold: 2
      connection:
        max-requests-per-connection: 1024
        pool:
          local:
            size: 2
          remote:
            size: 1
        set-keyspace-timeout: 25000
        max-orphan-requests: 256
  cassandra:
    contact-points: localhost
    port: 9042
    keyspace-name: iqe
    local-datacenter: datacenter1
    # username:
    # password:
    request:
      consistency: LOCAL_QUORUM
      timeout: 25000
    connection:
      init-query-timeout: 25000
      connect-timeout: 25000



# Logging
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.cvshealth.digital.microservice.dhsschedulingiqeservice: INFO
    com:
      cvshealth:
        digital: INFO
  pattern:
    console: "%msg%n"

# Open Tracing
opentracing:
  jaeger:
    enabled: true
    probabilistic-sampler:
      sampling-rate: 0.1 # Recommended 1.0 for Non-prod and 0.1 for Prod & PT
    log-spans: true
    http-sender:
      url: http://jaeger-collector.istio-system.svc:14268/api/traces

# Api Documentation
springdoc:
  api-docs:
    enabled: true
    path: /scheduling/iqe/v3/api-docs
  swagger-ui:
    path: /scheduling/iqe/swagger-ui.html
    config-url: /scheduling/iqe/v3/api-docs/swagger-config
    url: /scheduling/iqe/v3/api-docs
    disable-swagger-default-url: true
  paths-to-exclude: /swagger-resources/**, /v2/api-docs

springfox:
  documentation:
    auto-startup: false

# Server Configuration
server:
  port: 21140
  max-http-request-header-size: 10MB

# Liveness Probe Config
livenessProbe:
  httpGet:
    path: /scheduling/iqe/actuator/health/liveness
    port: 21140
    initialDelaySeconds: 5
    periodSeconds: 5


# Readiness Probe Config
readinessProbe:
  httpGet:
    path: /scheduling/iqe/actuator/health/readiness
    port: 21140
    initialDelaySeconds: 5
    periodSeconds: 5

management:
  health:
    probes:
      enabled: true
    circuitbreakers:
      enabled: false
  endpoints:
    web:
      base-path: /scheduling/iqe/actuator
      exposure:
        include: prometheus,health
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    tags:
      application: dhs-scheduling-iqe-service
api:
  configs:
    iqe:
      getIQEMcCoreQuestionnarie:
        baseUrl: https://internal-uat-test-east.digital-healthservices.cvs.com/schedule/iqe/v1/getquestionnairerules
        readTimeout: 3000
        connectionTimeout: 3000
      dynamicFlowConditionEvaluation:
        baseUrl: https://uat-test-east.digital-healthservices.cvs.com/schedule/iqe/v1/questionnaires/dynamic-flow-condition-evaluation
        readTimeout: 3000
        connectionTimeout: 3000
    appointment:
      getAppointment:
              baseUrl: http://localhost:21139
              uri: /schedule/core/v1/appointmentdata
              readTimeout: 1000
              connectionTimeout: 1000


feature:
  live:
    getEligibleVaccinesExpanded: true
    getEligibleVaccinesCareGaps: false
    mcCareGap: true
    enableVmAppointmentStatus: false
    checkInApptStatusEnabled: true
    isInsuranceDomainSavePatientInsuranceEnabled: true
    directEPHFailureToEPIC: true
    enableSchedulingConsents: true
    mcGroupScheduling: true
    isStateRestrictedEnabled: true
    enhanced-redis-caching: true
    dataset-snapshot-caching: true    # Strategy 1 feature flag
    cassandra-first-reads: true      # Cassandra as primary for all reads
    redis-fallback-only: true       # Redis only during Cassandra outages
    seamless-fallback: true         # Enable seamless Redis fallback

state-minor-age-limit:
  config:
    AL: 19
    NE: 19
    MS: 21
    default: 18

cvs:
  feature:
    isEvc: "false"
    isSLCapability: true
    isGetEligibleVaccinesV2Enabled: true
    isVaccineIntakeEnabled: "true"
    isVMAppointmentDetailsEnabled: true
    enableProviderApptCancel: true
    isLogNeeded: true
    isCaptureInsuranceSchedulingEnabled: true
    isMCVaccineIntakeFormEnabled: true

#app related data
app:
  name: dhs-scheduling-iqe-service
#  type: "java"
#  enableOpenTelemetry: "true"



custom:
  env: UAT3
  referer: https://www.cvs.com
  logHttpHeaders: GRID,user-agent,referer
  QuestionnaireContexts:
    mciqe: questionaire/mc_iqe_questions.json
  consentsConfig:
    VACCINE: "src/main/resources/consents/consents_vaccine.json"
shortid:
  length: 6


