package com.cvshealth.digital.microservice.iqe.constants;

import java.util.List;

public class DhsCoreConstants {
    public static final String GRANT_TYPE_KEY = "grant_type";
    public static final String GRANT_TYPE_VALUE = "client_credentials";
    public static final String SCOPE_KEY = "scope";
    public static final String SCOPE_VALUE = "APPPHI APPPII";
    public static final String CVS_EVENT_KEY = "CVSEVENT";
    public static final String CLASSNAME = "className";
    public static final String SERVICE_NAME = "serviceName";
    public static final String METHOD_NAME = "methodName";
    public static final String SERVICE_DESC = "serviceDesc";
    public static final String OPNAME = "opName";
    public static final String CONST_USER_ID = "user_id";
    public static final String CONST_CATEGORY = "cat";
    public static final String CONST_EVENT_TYPE = "event-type";
    public static final String DEFAULT_CAT = "NGS_DOMAIN";
    public static final String CONST_DEFAULT_CATEGORY = "ngs";
    public static final String CONST_CHAN_PLAT = "chPlat";
    public static final String CONST_APP_NAME = "appName";
    public static final String CONST_DEVICE_TYPE = "deviceType";
    public static final String CONST_REQ_APP_VERSION = "AppVersion";
    public static final String CONST_APP_VERSION = "appVersion";
    public static final String CONST_CLIENT_IP = "clientIP";
    public static final String CONST_X_FINGERPRINT_ID = "x-client-fingerprint-id";
    public static final String CONST_X_STATE_ID = "x-state-id";
    public static final String CONST_X_CAT = "x-cat";
    public static final String CONST_X_CORRELATIONID = "x-correlationid";
    public static final String CONST_AKAMAI_CLIENT_IP = "cvs-akclient-ip";
    public static final String CONST_X_B3_PARENTSPANID = "x_b3_parentspanid";
    public static final String CONST_X_B3_SAMPLED = "x_b3_sampled";
    public static final String CONST_X_B3_SPANID = "x_b3_spanid";
    public static final String CONST_X_B3_TRACEID = "x_b3_traceid";
    public static final String CONST_EXP_ID = "x-experienceid";
    public static final String CONST_SRC_LOC_CD = "src_loc_cd";
    public static final String CONST_MSG_SRC_CD = "msg_src_cd";
    public static final String CONST_ORIGIN = "origin";
    public static final String CONST_X_APPNAME = "x-appname";
    public static final String CONST_CLIENT_ADDR = "clientAddr";
    public static final String CONST_REQ_ORIGIN = "req_origin";
    public static final String CONST_ENV = "env";
    public static final String CONST_USER_AGENT = "user-agent";
    public static final String CONST_REFERER = "referer";
    public static final String CONST_GRID = "grid";
    public static final String CONST_X_GRID = "x-grid";
    public static final String CONST_CLIENTREFID = "x-clientrefid";
    public static final String RESP_TIME = "respTime";
    public static final String STATUS_CDE = "statusCde";
    public static final String STATUS_MESSAGE = "statusMessage";
    public static final String STATUS_DESCRIPTION = "statusDescription";
    public static final String HTTP_STATUS_CDE = "httpStatusCde";
    public static final String SUCCESS_MSG = "SUCCESS";
    public static final String PARTIAL_SUCCESS_MSG = "PARTIAL_SUCCESS";
    public static final String SUCCESS_CODE = "0000";
    public static final String PARTIAL_SUCCESS_CODE = "0001";
    public static final String INTERNAL_SERVER_ERROR_CODE = "9999";
    public static final String NOT_FOUND_CODE = "5013";
    public static final String WARNING_MSG = "WARNING";
    public static final String FAILURE_MSG = "FAILURE";
    public static final String MCIT_USER_ID = "Digital";
    public static final String MCIT_APPLICATION_NAME = "MCDigital";
    public static final String CSN_BAD_REQUEST_ERR_TITLE = "confirmationNumber should not be empty";
    public static final String MM_DD_YYYY = "MM/dd/yyyy";
    public static final String YYYY_MM_DD = "yyyy-MM-dd";
    public static final String YYYY_MM_DD_HH_MM_SS = "yyyy-MM-dd HH:mm:ss";
    public static final String YYYY_MM_DD_HH_MM = "yyyy-MM-dd HH:mm";
    public static final String MM_DD_YYYY_HH_MM_SS = "MM/dd/yyyy HH:mm:ss";
    public static final String MM_DD_YYYY_HH_MM = "MM/dd/yyyy HH:mm";
    public static final String HH_MM_SS = "HH:mm:ss";
    public static final String HH_MM_A = "hh:mm a";
    public static final String HH_MM = "HH:mm";
    public static final String TIMEZONE_FORMAT = "yyyy-MM-dd'T'HH:mm'['VV']'";
    public static final Integer JOIN_LINK_SEND_TIME_DIFFERENCE_MINS = 10;
    public static final List<String> EMAIL_SUBMIT_COMPOSITE_DATA = List.of("apptDate", "apptTime", "confirmationNumber", "apptTimezone", "clinicId", "xid", "preferredName");
    public static final List<String> SMS_SUBMIT_COMPOSITE_DATA = List.of("apptDate", "apptTime", "joinLinkSendTime", "xid", "preferredName");
    public static final List<String> DEF_EMAIL_SUBMIT_COMPOSITE_DATA = List.of("rfv", "reasonId", "xid", "preferredName");
    public static final List<String> DEF_SMS_SUBMIT_COMPOSITE_DATA = List.of("confirmationNumber", "address", "xid", "dayMonthYear", "formattedTime", "timeOfDay", "preferredName");
    public static final List<String> COMMON_CANCEL_COMPOSITE_DATA = List.of("apptDate", "apptTime", "confirmationNumber", "apptTimezone", "clinicId", "initiatedBy", "cancelReason", "scheduledType", "preferredName");
    public static final List<String> DEF_EMAIL_CANCEL_COMPOSITE_DATA = List.of("apptDate", "apptTime", "apptTimezone", "clinicId", "initiatedBy", "cancelReason", "reasonId", "preferredName");
    public static final List<String> DEF_SMS_CANCEL_COMPOSITE_DATA = List.of("apptTime", "initiatedBy", "apptDateSMS", "preferredName");
    public static final List<String> templateIds = List.of("200", "609");
    public static final List<String> flowSheetIds = List.of("5698", "16598");
    public static final String MC_WEB = "MC_WEB";
    public static final String WEB = "WEB";
    public static final String CVS_EVENT = "CVSEVENT";
    public static final String ENTRY = "ENTRY";
    public static final String EXIT = "EXIT";
    public static final String INFO = "INFO";
    public static final String ERROR = "ERROR";

    public DhsCoreConstants() {
    }
}